# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SXSW' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SXSW
  pod 'PopupDialog', '~> 0.7'
  pod 'Firebase/Auth'
end
